# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DogApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DogApp
  pod 'Material'
  pod 'Alamofire', '~> 4.7'

  target 'DogAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DogAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
